create table tb_document_storage (id int8 generated by default as identity, created_at TIMESTAMP WITHOUT TIME ZONE, description varchar(255), document_file varchar(255), name varchar(255), updated_at TIMESTAMP WITHOUT TIME ZONE, primary key (id));
INSERT INTO tb_document_storage (name, description, created_At) VALUES ('Books', 'map', NOW());
INSERT INTO tb_document_storage (name, description, created_At) VALUES ('Electronics', 'phone', NOW());
INSERT INTO tb_document_storage (name, description, created_At) VALUES ('Computers', 'mouse', NOW());
