create table tb_document_storage (id int8 generated by default as identity, created_at TIMESTAMP WITHOUT TIME ZONE, description varchar(255), document_file varchar(255), name varchar(255), updated_at TIMESTAMP WITHOUT TIME ZONE, primary key (id));
INSERT INTO tb_document_storage (name, description, created_At) VALUES ('Nota Fiscal', 'Compra de imovel', NOW());
INSERT INTO tb_document_storage (name, description, created_At) VALUES ('Comprovante', 'comprovante de imposto', NOW());
INSERT INTO tb_document_storage (name, description, created_At) VALUES ('Extrato', 'extrato referente ao mês (xx)', NOW());
